### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by grossjonas** [ArnaudValensi/xdg-menu-to-awesome-wm#1]
Could you please write a detailed HowTo?

**Comment by ArnaudValensi** [comment]
I wrote a "How To" in the REAMDE.md and I updated the script because I forgot debug print. If you have any problem do not hesitate to let me know.

**Comment by grossjonas** [comment]
Thanks for the "How To". Since I do not know how to lua or python works it helped a lot. I almost got it working. The script breaks after my submenu13 - i'll have a further look into that next week. Thanks a lot so far!
